import discord
from discord.ext import commands

def TranslateToAesthetic(string):
    string = string.replace("a", "ａ")
    string = string.replace("b", "ｂ")
    string = string.replace("c", "ｃ")
    string = string.replace("ç", "ç")
    string = string.replace("d", "ｄ")
    string = string.replace("e", "ｅ")
    string = string.replace("f", "ｆ")
    string = string.replace("g", "ｇ")
    string = string.replace("ğ", "ğ")
    string = string.replace("h", "ｈ")
    string = string.replace("ı", "ı")
    string = string.replace("i", "ｉ")
    string = string.replace("j", "ｊ")
    string = string.replace("k", "ｋ")
    string = string.replace("l", "ｌ")
    string = string.replace("m", "ｍ")
    string = string.replace("n", "ｎ")
    string = string.replace("o", "ｏ")
    string = string.replace("ö", "ö")
    string = string.replace("p", "ｐ")
    string = string.replace("r", "ｒ")
    string = string.replace("s", "ｓ")
    string = string.replace("ş", "ş")
    string = string.replace("u", "ｕ")
    string = string.replace("ü", "ü")
    string = string.replace("t", "ｔ")
    string = string.replace("x", "ｘ")
    string = string.replace("y", "ｙ")
    string = string.replace("z", "ｚ")
    string = string.replace("w", "ｗ")
    string = string.replace("q", "ｑ")

    string = string.replace("A", "Ａ")
    string = string.replace("B", "Ｂ")
    string = string.replace("C", "Ｃ")
    string = string.replace("Ç", "Ç")
    string = string.replace("D", "Ｄ")
    string = string.replace("E", "Ｅ")
    string = string.replace("F", "Ｆ")
    string = string.replace("G", "Ｇ")
    string = string.replace("Ğ", "Ğ")
    string = string.replace("H", "Ｈ")
    string = string.replace("I", "Ｉ")
    string = string.replace("İ", "İ")
    string = string.replace("J", "Ｊ")
    string = string.replace("K", "Ｋ")
    string = string.replace("L", "Ｌ")
    string = string.replace("M", "Ｍ")
    string = string.replace("N", "Ｎ")
    string = string.replace("O", "Ｏ")
    string = string.replace("Ö", "Ö")
    string = string.replace("P", "Ｐ")
    string = string.replace("R", "Ｒ")
    string = string.replace("S", "Ｓ")
    string = string.replace("Ş", "Ş")
    string = string.replace("U", "Ｕ")
    string = string.replace("Ü", "Ü")
    string = string.replace("T", "Ｔ")
    string = string.replace("X", "Ｘ")
    string = string.replace("Y", "Ｙ")
    string = string.replace("Z", "Ｚ")
    string = string.replace("W", "Ｗ")
    string = string.replace("Q", "Ｑ")

    string = string.replace("1", "１")
    string = string.replace("2", "２")
    string = string.replace("3", "３")
    string = string.replace("4", "４")
    string = string.replace("5", "５")
    string = string.replace("6", "６")
    string = string.replace("7", "７")
    string = string.replace("8", "８")
    string = string.replace("9", "９")
    string = string.replace("0", "０")

    string = string.replace("é", "é")
    string = string.replace("!", "！")
    string = string.replace("'", "＇")
    string = string.replace("^", "＾")
    string = string.replace("+", "＋")
    string = string.replace("%", "％")
    string = string.replace("&", "＆")
    string = string.replace("/", "／")
    string = string.replace("(", "（")
    string = string.replace(")", "）")
    string = string.replace("=", "＝")
    string = string.replace("?", "？")
    string = string.replace("_", "＿")
    string = string.replace(";", "；")
    string = string.replace(":", "：")

    string = string.replace(".", "．")
    string = string.replace(",", "，")

    string = string.replace("|", "｜")
    string = string.replace("<", "＜")
    string = string.replace(">", "＞")
    string = string.replace("£", "£")
    string = string.replace("#", "＃")
    string = string.replace("$", "＄")
    string = string.replace("½", "½")
    string = string.replace("{", "｛")
    string = string.replace("[", "［")
    string = string.replace("]", "］")
    string = string.replace("}", "｝")
    string = string.replace("~", "～")
    string = string.replace("`", "｀")
    string = string.replace("\\", "＼")
    return string


@client.command()
async def aesthetic(ctx, *, msg=None):
    if msg == None:
        embed = discord.Embed(title="", description=f":x: Lütfen Aesthetic Yazı İçin Bir Mesaj Giriniz.", color=0xff0000)
        await ctx.send(embed=embed, delete_after=5)
        return

    if len(msg) > 1024:
        embed = discord.Embed(title="", description=f":x: Mesaj En Fazla `1024` Karakterden Oluşabilir.", color=0xff0000)
        await ctx.send(embed=embed, delete_after=5)
        return

    translated_aesthetic_text = TranslateToAesthetic(msg)
    await ctx.send(f"```{translated_aesthetic_text}```")
